parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
#        types:
#            timestamp:  App\Type\Timestamp
#            datetime2:  App\Type\DateTimeTwo
        default_connection: default
        connections:
            default:
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4

                # With Symfony 3.3, remove the `resolve:` prefix
                url: '%env(resolve:DATABASE_URL)%'

            delta:
                # configure these for your database server
                driver: 'pdo_sqlsrv'
                server_version: '5.7'
                charset: utf8mb4
                schema_filter: ~^.*(^PARAMS*|^GROUPS*|^DEVICES*|^SCALES*|^SCRIPT_ENGINES*)~
                # With Symfony 3.3, remove the `resolve:` prefix
                url: '%env(resolve:DATABASE_DELTA_URL)%'
#                mapping_types:
#                    datetime2: datetime2
#                    timestamp: timestamp

            delta_data:
                # configure these for your database server
                driver: 'pdo_sqlsrv'
                server_version: '5.7'
                charset: utf8mb4
                schema_filter: ~^.*(^A01012019*|^D01012019*)~
                # With Symfony 3.3, remove the `resolve:` prefix
                url: '%env(resolve:DATABASE_DELTA_DATA_URL)%'



    orm:
#        auto_generate_proxy_classes: '%kernel.debug%'
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
#        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            delta:
                connection: delta
                mappings:
                    Customer:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Delta'
                        prefix: 'App\Entity\Delta'
                        alias: Delta
            delta_data:
                connection: delta_data
                mappings:
                    Customer:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Delta'
                        prefix: 'App\Entity\Delta'
                        alias: DeltaData