#all api section
nelmio_api_doc:
  documentation:
    info:
      title: Evrinoma Api
      description: LiveVideo api doc
      version: 1.1.2
  areas: # to filter documented areas
    evrinoma:
      path_patterns:
        - ^/evrinoma/api

contr_agent:
  db_driver: orm
  class: App\Entity\ContrAgent
#  entity_manager_name:

project:
  db_driver: orm
  class: App\Entity\Project
#  entity_manager_name:

#dashboard section
dashboard:
  #  infos:
  #    - 'Evrinoma\DashBoardBundle\Info\ProcInfo'
  #    - 'Evrinoma\DashBoardBundle\Info\SysInfo'
  provider: App\DashBoard\Provider\DashBoardProvider
#  menu: App\Menu\DashBoardMenu
#nelmio_api_doc:
#  documentation:
#    info:
#      title: DashBoard
#      description: DashBoard api doc
#      version: 1.0.2
#  areas: # to filter documented areas
#    dashboard:
#      path_patterns:
#        - ^/evrinoma/api/dashboard

#delta8 section
#delta8:
#  menu: App\Menu\Delta8Menu
#App\Menu\Delta8Menu:
#  tags:
#    - { name: evrinoma.menu }

#exim section
#exim:
#  menu: App\Menu\EximMenu
#App\Menu\EximMenu:
#  tags:
#    - { name: evrinoma.menu }
#nelmio_api_doc:
#  documentation:
#    info:
#      title: EximApi
#      description: Exim api doc
#      version: 1.0.2
#  areas: # to filter documented areas
#    exim:
#      path_patterns:
#          - ^/evrinoma/api/exim

#livevideo section
#livevideo:
#  menu: pp\Menu\LiveVideoMenu
#App\Menu\LiveVideoMenu:
#  tags:
#    - { name: evrinoma.menu }

#nelmio_api_doc:
#  documentation:
#    info:
#      title: LiveVideoApi
#      description: LiveVideo api doc
#      version: 1.0.2
#  areas: # to filter documented areas
#    live_video:
#      path_patterns:
#          - ^/evrinoma/api/live_video

utils:
  ldap_servers:
    ite-ng.ru:
      - { host: "ldap://iteng06.ite-ng.ru", port: "636", search: "OU=MSK,DC=ite-ng,DC=ru" }
      - { host: "ldap://iteng20.ite-ng.ru", port: "636", search: "OU=MSK,DC=ite-ng,DC=ru"}
    ur.ite-ng.ru:
      - { host: "ldap://ur04.ur.ite-ng.ru", port: "636", search: "OU=ekaterinburg,DC=ur,DC=ite-ng,DC=ru" }
      - { host: "ldap://ur05.ur.ite-ng.ru", port: "636", search: "OU=ekaterinburg,DC=ur,DC=ite-ng,DC=ru"}

doctrine:
  dbal:
    connections:
      delta:
        # configure these for your database server
        driver: 'pdo_sqlsrv'
        server_version: '5.7'
        charset: utf8mb4
        #        schema_filter: ~^.*(^PARAMS*|^GROUPS*|^DEVICES*|^SCALES*|^SCRIPT_ENGINES*)~
        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_DELTA_URL)%'
  orm:
    default_entity_manager: default
    entity_managers:
      delta8:
        connection: delta
        mappings:
          Customer:
            is_bundle: false
            type: annotation
            dir: '%kernel.project_dir%/vendor/evrinoma/delta8-bundle/src/Entity'
            prefix: 'Evrinoma\Delta8Bundle\Entity'
            alias: Delta