knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: menu\knp.html.twig
    templating: true # if true, enables the helper for PHP templates
    default_renderer: twig