<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    FOS\UserBundle\FOSUserBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    FOS\RestBundle\FOSRestBundle::class => ['all' => true],
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    Nelmio\ApiDocBundle\NelmioApiDocBundle::class => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    FOS\JsRoutingBundle\FOSJsRoutingBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    Evrinoma\ShellBundle\EvrinomaShellBundle::class => ['all' => true],
    Evrinoma\DashBoardBundle\EvrinomaDashBoardBundle::class => ['all' => true],
    Evrinoma\LiveVideoBundle\EvrinomaLiveVideoBundle::class => ['all' => true],
    Evrinoma\DtoBundle\EvrinomaDtoBundle::class => ['all' => true],
    Evrinoma\SettingsBundle\EvrinomaSettingsBundle::class => ['all' => true],
    Evrinoma\EximBundle\EvrinomaEximBundle::class => ['all' => true],
    Evrinoma\MenuBundle\EvrinomaMenuBundle::class => ['all' => true],
    Evrinoma\Delta8Bundle\EvrinomaDelta8Bundle::class => ['all' => true],
    Evrinoma\UtilsBundle\EvrinomaUtilsBundle::class => ['all' => true],
    Evrinoma\GridBundle\EvrinomaGridBundle::class => ['all' => true],
];
