#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#index:
#    path: /
#    controller: App\Controller\ArticleController::homepage

index:
    path: /
    controller: App\Controller\DisplayController::display